///////////////////////////////// Auth//////////////////////////////////////
//Register
export const REGISTER_USER_REQUEST = "REGISTER_USER_REQUEST";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_FAILURE = "REGISTER_USER_FAILURE";
//Login
export const LOGIN_USER_REQUEST = "LOGIN_USER_REQUEST";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_FAILURE = "LOGIN_USER_FAILURE";
// forgot password
export const FORGOT_PASSWORD_REQUEST = "FORGOT_PASSWORD_REQUEST";
export const FORGOT_PASSWORD_SUCCESS = "FORGOT_PASSWORD_SUCCESS";
export const FORGOT_PASSWORD_FAILURE = "FORGOT_PASSWORD_FAILURE";
// Reset password
export const RESET_PASSWORD_REQUEST = "RESET_PASSWORD_REQUEST";
export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS";
export const RESET_PASSWORD_FAILURE = "RESET_PASSWORD_FAILURE";
//checkAuth
export const CHECKAUTH_SUCCESS = "CHECKAUTH_SUCCESS";
export const CHECKAUTH_FAILURE = "CHECKAUTH_FAILURE";
export const SET_USER = "SET_USER";
// Alert
export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";

//////////////////////// Profile /////////////////////////////////////////
////////////////////////// ORGS///////////////////////////////////////////
//create an org
export const CREATE_ORGANIZATION_REQUEST = "CREATE_ORGANIZATION_REQUEST";
export const CREATE_ORGANIZATION_SUCCESS = "CREATE_ORGANIZATION_SUCCESS";
export const CREATE_ORGANIZATION_FAILURE = "CREATE_ORGANIZATION_FAILURE";
// get orgs
export const LOAD_ORGANIZATIONS_REQUEST = "LOAD_ORGANIZATIONS_REQUEST";
export const LOAD_ORGANIZATIONS_SUCCESS = "LOAD_ORGANIZATIONS_SUCCESS";
export const LOAD_ORGANIZATIONS_FAILURE = "LOAD_ORGANIZATIONS_FAILURE";
// delete an org
export const DELETE_ORGANIZATION_REQUEST = "DELETE_ORGANIZATION_REQUEST";
export const DELETE_ORGANIZATION_SUCCESS = "DELETE_ORGANIZATION_SUCCESS";
export const DELETE_ORGANIZATION_FAILURE = "DELETE_ORGANIZATION_FAILURE";
// updates an org
export const UPDATE_ORGANIZATION_REQUEST = "UPDATE_ORGANIZATION_REQUEST";
export const UPDATE_ORGANIZATION_SUCCESS = "UPDATE_ORGANIZATION_SUCCESS";
export const UPDATE_ORGANIZATION_FAILURE = "UPDATE_ORGANIZATION_FAILURE";
export const SET_CURRENT_ORG = "SET_CURRENT_ORG";
// WhatToShow
export const SHOW_TABLE = "SHOW_TABLE";
export const SHOW_FORM = "SHOW_FORM";
export const SHOW_UPDATEFORM = "SHOW_UPDATEFORM";
export const SHOW_WINDOW = "SHOW_WINDOW";

////////////////////////// CLIENTS///////////////////////////////////////////
//create client
export const CREATE_CLIENT_REQUEST = "CREATE_CLIENT_REQUEST";
export const CREATE_CLIENT_SUCCESS = "CREATE_CLIENT_SUCCESS";
export const CREATE_CLIENT_FAILURE = "CREATE_CLIENT_FAILURE";
// get clients
export const LOAD_CLIENT_REQUEST = "LOAD_CLIENT_REQUEST";
export const LOAD_CLIENT_SUCCESS = "LOAD_CLIENT_SUCCESS";
export const LOAD_CLIENT_FAILURE = "LOAD_CLIENT_FAILURE";
// delete a client
export const DELETE_CLIENT_REQUEST = "DELETE_CLIENT_REQUEST";
export const DELETE_CLIENT_SUCCESS = "DELETE_CLIENT_SUCCESS";
export const DELETE_CLIENT_FAILURE = "DELETE_CLIENT_FAILURE";
// updates a client
export const UPDATE_CLIENT_REQUEST = "UPDATE_CLIENT_REQUEST";
export const UPDATE_CLIENT_SUCCESS = "UPDATE_CLIENT_SUCCESS";
export const UPDATE_CLIENT_FAILURE = "UPDATE_CLIENT_FAILURE";
export const SET_CURRENT_CLIENT = "SET_CURRENT_CLIENT";
// WhatToShow
export const SHOW_TABLE_ORGANIZATIONSTOPICK = "SHOW_TABLE_ORGANIZATIONSTOPICK";
export const SHOW_TABLE_CLIENTS = "SHOW_TABLE_CLIENTS";
export const SHOW_FORM_CLIENTS = "SHOW_FORM_CLIENTS";
export const SHOW_UPDATEFORM_CLIENTS = "SHOW_UPDATEFORM_CLIENTS";
export const SHOW_WINDOW_CLIENTS = "SHOW_WINDOW_CLIENTS";
////////////////////////// PROJECTS///////////////////////////////////////////
// create  a project
export const CREATE_PROJECT_REQUEST = "CREATE_PROJECT_REQUEST";
export const CREATE_PROJECT_SUCCESS = "CREATE_PROJECT_SUCCESS";
export const CREATE_PROJECT_FAILURE = "CREATE_PROJECT_FAILURE";
// get projects
export const LOAD_PROJECT_REQUEST = "LOAD_PROJECT_REQUEST";
export const LOAD_PROJECT_SUCCESS = "LOAD_PROJECT_SUCCESS";
export const LOAD_PROJECT_FAILURE = "LOAD_PROJECT_FAILURE";
// delete a project
export const DELETE_PROJECT_REQUEST = "DELETE_PROJECT_REQUEST";
export const DELETE_PROJECT_SUCCESS = "DELETE_PROJECT_SUCCESS";
export const DELETE_PROJECT_FAILURE = "DELETE_PROJECT_FAILURE";
// updates a project
export const UPDATE_PROJECT_REQUEST = "UPDATE_PROJECT_REQUEST";
export const UPDATE_PROJECT_SUCCESS = "UPDATE_PROJECT_SUCCESS";
export const UPDATE_PROJECT_FAILURE = "UPDATE_PROJECT_FAILURE";
export const SET_CURRENT_PROJECT = "SET_CURRENT_PROJECT";
// whatToShow
export const SHOW_TABLE_ORGANIZATIONSFORPROJECTS = "SHOW_TABLE_ORGANIZATIONSFORPROJECTS";
export const SHOW_TABLE_CLIENTSTOPICK = "SHOW_TABLE_CLIENTSTOPICK";
export const SHOW_TABLE_PROJECTS = "SHOW_TABLE_PROJECTS";
export const SHOW_FORM_PROJECTS = "SHOW_FORM_PROJECTS";
export const SHOW_UPDATEFORM_PROJECTS = "SHOW_UPDATEFORM_PROJECTS";
export const SHOW_WINDOW_PROJECTS = "SHOW_WINDOW_PROJECTS";
